FROM ryanjohnson/ssh:latest

RUN pacman -S --noconfirm \
    base-devel \
    cmake \
    ctags \
    curl \
    diffutils \
    docker \
    entr \
    git \
    gtest \
    imagemagick \
    lastpass-cli \
    libwebp \
    lynx \
    ncurses \
    neovim \
    newsboat \
    nodejs \
    python \
    python-pip \
    python-virtualenv \
    vit \
    yarn \
;
